apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-transaction-pv-claim
  labels:
    app: mm-transaction
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
