apiVersion: v1
kind: Service
metadata:
  name: mm-transaction-mysql
  labels:
    app: mm-transaction
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app: mm-transaction
    tier: mysql
  type: ClusterIP
---
