apiVersion: v1
kind: Service
metadata:
  name: mm-transaction-api
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: mm-transaction-api
    tier: api
  type: ClusterIP
---