apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mm-transaction-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mm-transaction-api
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
---